server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      cookie:
        same-site: none
        secure: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbtisns
    username : root
    password: 12345789a
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: C:/Users/tj/CWT/Mb_Tiny/uploads

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR