server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      cookie:
        same-site: none
        secure: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbtisns
    username : root
    password: hsgty588123s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: D:/hsg/Mb_Tiny/uploads

custom:
  default-profile-img: /uploads/profile/default.png

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR