server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbtisns
    username : root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
