server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbtisns
    username : root
    password: xkfprk0011!~
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
